# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentops < Formula
  desc "Knowledge Flywheel CLI for AI-assisted development"
  homepage "https://github.com/boshu2/agentops"
  version "2.18.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/boshu2/agentops/releases/download/v2.18.0/ao-darwin-amd64.tar.gz"
      sha256 "97e6a29576293f1ec6006e1c1af58e4d9b55f64e54ed7d011b484d720a485115"

      define_method(:install) do
        bin.install "ao"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/boshu2/agentops/releases/download/v2.18.0/ao-darwin-arm64.tar.gz"
      sha256 "8c74a2aa5800914ad147aedd1a82dc31ffa5b88a83430c636fb1e550c70aea4f"

      define_method(:install) do
        bin.install "ao"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/boshu2/agentops/releases/download/v2.18.0/ao-linux-amd64.tar.gz"
      sha256 "8b4880811e5091bca2f7a2b376bfb5ba74d8f79bdfb94a7484d0f0e8f14137e0"
      define_method(:install) do
        bin.install "ao"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boshu2/agentops/releases/download/v2.18.0/ao-linux-arm64.tar.gz"
      sha256 "900d4da268154aae418bddb6913ca8b1e77896a9042bc0c5c61f1729e6b8ec65"
      define_method(:install) do
        bin.install "ao"
      end
    end
  end

  def post_install
    system "codesign", "-f", "-s", "-", "-i", "com.12factoragentops.ao", "#{bin}/ao" if OS.mac?
  end

  test do
    system "#{bin}/ao version"
  end
end
